language: php

matrix:
    fast_finish: true
    include:
          # Test with lowest dependencies
        - php: 7.2
          env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest" SYMFONY_DEPRECATIONS_HELPER="weak"

        - php: 7.3
        - php: 7.4

          # Latest commit to master
        - php: 7.4
          env: STABILITY="dev"

    allow_failures:
          # Dev-master is allowed to fail.
        - env: STABILITY="dev"

addons:
    apt:
        packages:
            - rabbitmq-server

services:
    - rabbitmq

before_install:
    - phpenv config-rm xdebug.ini || true
    - if ! [ -z "$STABILITY" ]; then composer config minimum-stability ${STABILITY}; fi;
    - sudo rabbitmq-plugins enable rabbitmq_management

before_script:
    - composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction
    - php rabbit vhost:reset my_vhost_name -p guest
    - php rabbit vhost:mapping:create examples/events.yml -p guest

script:
    - composer validate --strict --no-check-lock
    - vendor/bin/phpunit
