sudo: false

language: php

php:
  - 7.1
  - 7.2

addons:
    apt:
        packages:
            - rabbitmq-server

services:
    - rabbitmq

before_install:
    - composer self-update --stable --no-interaction

before_script:
    - composer install --prefer-source --no-interaction

script:
    - php rabbit vhost:reset my_vhost_name -p guest
    - php rabbit vhost:mapping:create examples/events.yml -p guest
    - vendor/bin/phpunit
