name: Static code analysis

on: [pull_request]

jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run PHPStan
        uses: docker://jakzal/phpqa:latest
        with:
          args: phpstan analyze

  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run PHP-CS-Fixer
        uses: docker://jakzal/phpqa:latest
        with:
            args: php-cs-fixer fix --dry-run -vvv --diff
